language: php

php:
  - 5.6

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update
  - composer require satooshi/php-coveralls

script:
  - ./vendor/bin/phpunit --coverage-clover /tmp/clover.xml

after_success:
  - php vendor/bin/coveralls -v
