language: php

php:
  - 5.6

before_install:
  - composer self-update
  - composer install

install:
  - mkdir -p build/logs
  - composer require satooshi/php-coveralls

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v
