language: php

php:
  - 5.6

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update 

script:
  - ./vendor/bin/phpunit --coverage-clover /tmp/bee-game-coverage-clover.xml
